### ISSUE TITLE
Can't add .git link to Plugin Manager

### ISSUE THREAD

**Issue by spencerrecneps** [anitagraser/QGIS-resource-collections#4]
Hi Anita. The README indicates that I can add this to my plugins by adding the .git link: 

![image](https://cloud.githubusercontent.com/assets/4584258/23032828/7922abfa-f43b-11e6-8e76-4d61e1229cc0.png)

When I do that I get an error:

![image](https://cloud.githubusercontent.com/assets/4584258/23032766/3163d97e-f43b-11e6-8f7f-68c44f3318a7.png)

Am I missing something? Thanks!

**Comment by anitagraser** [comment]
This repository is supposed to be added to the resource sharing plugin, not the plugin installer. 

Install the resource sharing plugin. This repo is already preconfigured.

**Comment by spencerrecneps** [comment]
Ah thanks. That makes sense now.
